/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<string | { url: string; revision: string }>;
};

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Take control of clients immediately
self.skipWaiting();
clientsClaim();

/**
 * Handle Web Share Target POST requests
 * Android Chrome sends a POST request with multipart/form-data when sharing files
 */
self.addEventListener('fetch', (event: FetchEvent) => {
  const url = new URL(event.request.url);

  // Check if this is our share target action
  if (event.request.method === 'POST' && url.pathname.endsWith('/share')) {
    event.respondWith(
      (async () => {
        try {
          const formData = await event.request.formData();
          const title = formData.get('title') as string | null;
          const text = formData.get('text') as string | null;
          const sharedUrl = formData.get('url') as string | null;
          const files = formData.getAll('files') as File[];

          // Store in IndexedDB
          const dbName = 'clipshare-share-db';
          const storeName = 'incoming';
          
          const db = await new Promise<IDBDatabase>((resolve, reject) => {
            const request = indexedDB.open(dbName, 1);
            request.onupgradeneeded = () => {
              const db = request.result;
              if (!db.objectStoreNames.contains(storeName)) {
                db.createObjectStore(storeName);
              }
            };
            request.onsuccess = () => resolve(request.result);
            request.onerror = () => reject(request.error);
          });

          const tx = db.transaction(storeName, 'readwrite');
          const store = tx.objectStore(storeName);
          
          await new Promise<void>((resolve, reject) => {
            const putRequest = store.put({
              title,
              text,
              url: sharedUrl,
              files,
              receivedAt: Date.now()
            }, 'latest');
            putRequest.onsuccess = () => resolve();
            putRequest.onerror = () => reject(putRequest.error);
          });

          // Redirect to the /share page which will handle the UI
          // Use 303 See Other to ensure the browser performs a GET request
          // Important: Redirect to a relative URL from the action path
          return Response.redirect('./share?received=true', 303);
        } catch (error) {
          console.error('Error handling share target:', error);
          // Fallback to home with error flag
          return Response.redirect('./?error=share_failed', 303);
        }
      })()
    );
  }
});
